version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  test:
    executor: win/default
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip
            python -m pip install -e .
            python -m pip install tox==3.24.3

      - run:
          name: Run tests
          command: tox

workflows:
  windows-tests:
    jobs:
      - test
