version: 2.1

jobs:
  test:
    machine:
      image: windows-default
    resource_class: windows.medium
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip
            python -m pip install -e .
            python -m pip install tox

      - run:
          name: Run tests
          command: tox

workflows:
  windows-tests:
    jobs:
      - test
